# Railway (Nixpacks) qurilish sozlamalari
[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1 --proxy-headers --forwarded-allow-ips=\"*\" --no-server-header --timeout-keep-alive 65"
